export const salesItems = [
  // {
  //   id: 1,
  //   date: new Date().toLocaleDateString(),
  //   name: "Chanise Cabbage",
  //   price: "$14.99",
  // },
  // {
  //   id: 2,
  //   date: new Date().toLocaleDateString(),
  //   fi: "Green Lettuce",
  //   price: "$14.99",
  // },
  // {
  //   id: 3,
  //   date: new Date().toLocaleDateString(),
  //   name: "Green Chili",
  //   price: "$14.99",
  // },
  // {
  //   id: 4,
  //   date: new Date().toLocaleDateString(),
  //   name: "Corn",
  //   price: "$14.99",
  // },

  {
    id: 1,
    date: "2/3/2024",
    firstname: "Loni",
    lastname: "Genny",
    money: "$5.01",
  },
  {
    id: 2,
    date: "4/7/2024",
    firstname: "Reggie",
    lastname: "O'Tuohy",
    money: "$2.79",
  },
  {
    id: 3,
    date: "9/28/2023",
    firstname: "Shandeigh",
    lastname: "Glader",
    money: "$4.69",
  },
  {
    id: 4,
    date: "5/26/2024",
    firstname: "Sheila-kathryn",
    lastname: "Handsheart",
    money: "$1.38",
  },
  {
    id: 5,
    date: "6/26/2024",
    firstname: "Orson",
    lastname: "Loverock",
    money: "$0.60",
  },
  {
    id: 6,
    date: "3/11/2024",
    firstname: "Lesley",
    lastname: "Charteris",
    money: "$0.98",
  },
  {
    id: 7,
    date: "4/17/2024",
    firstname: "Shela",
    lastname: "Mallard",
    money: "$2.68",
  },
  {
    id: 8,
    date: "5/23/2024",
    firstname: "Rolfe",
    lastname: "Chimenti",
    money: "$2.40",
  },
  {
    id: 9,
    date: "11/14/2023",
    firstname: "Bettye",
    lastname: "Daily",
    money: "$8.76",
  },
  {
    id: 10,
    date: "7/28/2024",
    firstname: "Fredelia",
    lastname: "Arstall",
    money: "$6.78",
  },
  {
    id: 11,
    date: "1/22/2024",
    firstname: "Ryann",
    lastname: "Cutchee",
    money: "$7.66",
  },
  {
    id: 12,
    date: "7/27/2024",
    firstname: "Whitaker",
    lastname: "Craigg",
    money: "$4.39",
  },
  {
    id: 13,
    date: "1/7/2024",
    firstname: "Minda",
    lastname: "Grigoli",
    money: "$5.12",
  },
  {
    id: 14,
    date: "2/28/2024",
    firstname: "Maurise",
    lastname: "Gristwood",
    money: "$5.43",
  },
  {
    id: 15,
    date: "9/4/2024",
    firstname: "Lotty",
    lastname: "Odell",
    money: "$3.46",
  },
  {
    id: 16,
    date: "7/22/2024",
    firstname: "Cathleen",
    lastname: "Leitch",
    money: "$8.27",
  },
  {
    id: 17,
    date: "5/21/2024",
    firstname: "Harmonia",
    lastname: "Beel",
    money: "$4.79",
  },
  {
    id: 18,
    date: "7/12/2024",
    firstname: "Lexie",
    lastname: "Currin",
    money: "$4.09",
  },
  {
    id: 19,
    date: "10/26/2023",
    firstname: "Claribel",
    lastname: "Kedie",
    money: "$4.82",
  },
  {
    id: 20,
    date: "11/26/2023",
    firstname: "Briano",
    lastname: "Aldwich",
    money: "$1.71",
  },
  {
    id: 21,
    date: "8/28/2024",
    firstname: "Erina",
    lastname: "Casero",
    money: "$5.34",
  },
  {
    id: 22,
    date: "2/4/2024",
    firstname: "Ingram",
    lastname: "Rackam",
    money: "$4.52",
  },
  {
    id: 23,
    date: "4/26/2024",
    firstname: "Else",
    lastname: "Muriel",
    money: "$1.24",
  },
  {
    id: 24,
    date: "6/14/2024",
    firstname: "Derril",
    lastname: "Lamanby",
    money: "$7.01",
  },
  {
    id: 25,
    date: "8/17/2024",
    firstname: "Fredek",
    lastname: "Smitten",
    money: "$5.51",
  },
  {
    id: 26,
    date: "3/4/2024",
    firstname: "Carlen",
    lastname: "Pucker",
    money: "$4.53",
  },
  {
    id: 27,
    date: "3/6/2024",
    firstname: "Aldwin",
    lastname: "Phippen",
    money: "$3.66",
  },
  {
    id: 28,
    date: "6/1/2024",
    firstname: "Evvie",
    lastname: "Monks",
    money: "$4.92",
  },
  {
    id: 29,
    date: "2/2/2024",
    firstname: "Shane",
    lastname: "Searsby",
    money: "$9.47",
  },
  {
    id: 30,
    date: "8/8/2024",
    firstname: "Wilone",
    lastname: "Saxelby",
    money: "$4.34",
  },
  {
    id: 31,
    date: "7/16/2024",
    firstname: "Minna",
    lastname: "Newbold",
    money: "$2.15",
  },
  {
    id: 32,
    date: "5/11/2024",
    firstname: "Megen",
    lastname: "Woakes",
    money: "$2.77",
  },
  {
    id: 33,
    date: "12/16/2023",
    firstname: "Barbey",
    lastname: "Renn",
    money: "$2.41",
  },
  {
    id: 34,
    date: "10/31/2023",
    firstname: "Friedrich",
    lastname: "Whittock",
    money: "$6.50",
  },
  {
    id: 35,
    date: "9/23/2023",
    firstname: "Tremayne",
    lastname: "Metschke",
    money: "$6.06",
  },
  {
    id: 36,
    date: "7/11/2024",
    firstname: "Garnette",
    lastname: "Hadaway",
    money: "$2.63",
  },
  {
    id: 37,
    date: "6/2/2024",
    firstname: "Renato",
    lastname: "Tybalt",
    money: "$8.65",
  },
  {
    id: 38,
    date: "2/19/2024",
    firstname: "Caritta",
    lastname: "Boanas",
    money: "$3.45",
  },
  {
    id: 39,
    date: "4/4/2024",
    firstname: "Fiona",
    lastname: "Katzmann",
    money: "$0.09",
  },
  {
    id: 40,
    date: "5/27/2024",
    firstname: "Audrie",
    lastname: "Dupre",
    money: "$3.98",
  },
  {
    id: 41,
    date: "8/12/2024",
    firstname: "Ardine",
    lastname: "Matschek",
    money: "$4.87",
  },
  {
    id: 42,
    date: "1/15/2024",
    firstname: "Angelica",
    lastname: "Fossick",
    money: "$1.16",
  },
  {
    id: 43,
    date: "2/28/2024",
    firstname: "Billi",
    lastname: "MacShane",
    money: "$4.69",
  },
  {
    id: 44,
    date: "7/17/2024",
    firstname: "Carry",
    lastname: "Dmytryk",
    money: "$6.48",
  },
  {
    id: 45,
    date: "9/28/2023",
    firstname: "Jayme",
    lastname: "Bastian",
    money: "$3.01",
  },
  {
    id: 46,
    date: "12/4/2023",
    firstname: "Hendrick",
    lastname: "Addeycott",
    money: "$2.76",
  },
  {
    id: 47,
    date: "12/16/2023",
    firstname: "Becca",
    lastname: "Mackie",
    money: "$2.75",
  },
  {
    id: 48,
    date: "3/9/2024",
    firstname: "Ralph",
    lastname: "Van Halen",
    money: "$8.64",
  },
  {
    id: 49,
    date: "10/3/2023",
    firstname: "Colly",
    lastname: "Mallindine",
    money: "$3.72",
  },
  {
    id: 50,
    date: "2/18/2024",
    firstname: "Orelie",
    lastname: "Sive",
    money: "$8.05",
  },
 
];
